// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export const DevTokenPath = "/api/dev/token";
export interface TokenResponse {
  token: string;
  ws_url: string;
}
export interface ErrorResponse {
  error: string;
}
