// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export const DevTokenPath = "/api/dev/token";
export const AuthLoginPath = "/api/auth/login";
export const AuthCallbackPath = "/api/auth/callback";
export const AuthLogoutPath = "/api/auth/logout";
export const MePath = "/api/me";
export const RoomsPath = "/api/rooms";
export const RoomPath = "/api/rooms/{slug}";
export const RoomJoinPath = "/api/rooms/{slug}/join";
export const RoomLobbyPath = "/api/rooms/{slug}/lobby";
export const KickPath = "/api/rooms/{slug}/participants/{identity}/kick";
export const MutePath = "/api/rooms/{slug}/participants/{identity}/mute";
export const LobbyWaitPath = "/api/lobby/{id}/wait";
export const LobbyApprovePath = "/api/lobby/{id}/approve";
export const LobbyDenyPath = "/api/lobby/{id}/deny";
export const LiveKitWebhookPath = "/api/webhooks/livekit";
export const RecordingStartPath = "/api/rooms/{slug}/recording/start";
export const RecordingStopPath = "/api/rooms/{slug}/recording/stop";
export const RoomRecordingsPath = "/api/rooms/{slug}/recordings";
export const RecordingPath = "/api/recordings/{id}";
export const RecordingDownloadPath = "/api/recordings/{id}/download";
export interface TokenResponse {
  token: string;
  ws_url: string;
}
export interface ErrorResponse {
  error: string;
}
export interface Me {
  sub: string;
  email: string;
  name: string;
}
export interface RoomInfo {
  id: string;
  slug: string;
  name: string;
  lobby_enabled: boolean;
  created_at: number /* int64 */;
}
export interface PublicRoomInfo {
  slug: string;
  name: string;
  lobby_enabled: boolean;
  /**
   * IsOwner is true when the requesting session owns this room; the
   * capability itself is still enforced server-side on every route.
   */
  is_owner: boolean;
}
export interface CreateRoomRequest {
  name: string;
}
export interface UpdateRoomRequest {
  name?: string;
  lobby_enabled?: boolean;
}
export interface JoinRequest {
  name: string;
}
export interface JoinResponse {
  status: string;
  token?: string;
  ws_url?: string;
  request_id?: string;
}
export interface LobbyRequestInfo {
  id: string;
  name: string;
  requested_at: number /* int64 */;
}
export interface LobbyWaitingSSE {
  status: string;
}
export interface LobbyAdmittedSSE {
  token: string;
  ws_url: string;
}
export interface LobbyDeniedSSE {
}
export interface LobbyPendingSSE {
  requests: LobbyRequestInfo[];
}
export interface RecordingInfo {
  id: string;
  room_slug: string;
  egress_id: string;
  status: string;
  started_by: string;
  started_at: number /* int64 */;
  ended_at?: number /* int64 */;
  duration_s?: number /* int64 */;
  s3_key?: string;
  size_bytes?: number /* int64 */;
}
