package media

import (
	"slices"
	"testing"
)

func TestLivekitConfig(t *testing.T) {
	opts := Options{
		APIKey: testKey, APISecret: testSecret, Loopback: true,
		InternalPort: 17880, TCPPort: 17881, UDPPort: 17882,
		WebhookURL: "http://127.0.0.1:8080/api/webhooks/media",
		RedisAddr:  "redis:6379", RedisPassword: testRedisPassword,
	}
	conf, err := livekitConfig(opts)
	if err != nil {
		t.Fatal(err)
	}
	if conf.Port != 17880 || !slices.Equal(conf.BindAddresses, []string{"127.0.0.1"}) {
		t.Errorf("API on %v:%d, want 127.0.0.1:17880 only", conf.BindAddresses, conf.Port)
	}
	if conf.RTC.TCPPort != 17881 || conf.RTC.UDPPort.Start != 17882 || conf.RTC.UDPPort.End != 0 {
		t.Errorf("media ports tcp %d udp %+v, want 17881 and the single port 17882", conf.RTC.TCPPort, conf.RTC.UDPPort)
	}
	if conf.RTC.NodeIP.V4 != "127.0.0.1" || conf.RTC.UseExternalIP || !conf.RTC.EnableLoopbackCandidate {
		t.Errorf("loopback node: ip %+v, external %v, loopback candidate %v",
			conf.RTC.NodeIP, conf.RTC.UseExternalIP, conf.RTC.EnableLoopbackCandidate)
	}
	if conf.Keys[testKey] != testSecret || len(conf.Keys) != 1 {
		t.Errorf("keys: %d configured", len(conf.Keys))
	}
	if conf.WebHook.APIKey != testKey || !slices.Equal(conf.WebHook.URLs, []string{opts.WebhookURL}) {
		t.Errorf("webhook: key %q, urls %v", conf.WebHook.APIKey, conf.WebHook.URLs)
	}
	if conf.Redis.Address != "redis:6379" || conf.Redis.Password != testRedisPassword {
		t.Errorf("redis at %q, want redis:6379 with its password", conf.Redis.Address)
	}
	if conf.Logging.Level != "warn" || conf.Room.DepartureTimeout != 20 {
		t.Errorf("production: log level %q, departure timeout %ds; want warn and LiveKit's 20s",
			conf.Logging.Level, conf.Room.DepartureTimeout)
	}

	opts.Dev = true
	dev, err := livekitConfig(opts)
	if err != nil {
		t.Fatal(err)
	}
	if dev.Logging.Level != "info" || dev.Room.DepartureTimeout != 5 {
		t.Errorf("dev: log level %q, departure timeout %ds; want info and 5s",
			dev.Logging.Level, dev.Room.DepartureTimeout)
	}
}

func TestLivekitConfigAdvertisesAGivenNodeIP(t *testing.T) {
	conf, err := livekitConfig(Options{
		APIKey: testKey, APISecret: testSecret, NodeIP: "10.253.0.4",
		InternalPort: 17880, TCPPort: 17881, UDPPort: 17882,
	})
	if err != nil {
		t.Fatal(err)
	}
	if conf.RTC.NodeIP.V4 != "10.253.0.4" || conf.RTC.NodeIPAutoGenerated || conf.RTC.UseExternalIP {
		t.Errorf("node ip %+v (auto %v, external %v), want 10.253.0.4 as given",
			conf.RTC.NodeIP, conf.RTC.NodeIPAutoGenerated, conf.RTC.UseExternalIP)
	}
	if conf.RTC.EnableLoopbackCandidate {
		t.Error("a LAN node IP enables loopback candidates")
	}
	if conf.Redis.Address != "" {
		t.Errorf("redis at %q when none was named", conf.Redis.Address)
	}
}
