apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tide.yaml
  - media.yaml
  - redis.yaml
  - recorder.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: tide
    includeSelectors: false
