package api

const (
	DevTokenPath          = "/api/dev/token"
	AuthLoginPath         = "/api/auth/login"
	AuthCallbackPath      = "/api/auth/callback"
	AuthLogoutPath        = "/api/auth/logout"
	MePath                = "/api/me"
	RoomsPath             = "/api/rooms"
	RoomPath              = "/api/rooms/{slug}"
	RoomJoinPath          = "/api/rooms/{slug}/join"
	RoomLobbyPath         = "/api/rooms/{slug}/lobby"
	KickPath              = "/api/rooms/{slug}/participants/{identity}/kick"
	MutePath              = "/api/rooms/{slug}/participants/{identity}/mute"
	MeetingEndPath        = "/api/rooms/{slug}/meeting/end"
	LobbyWaitPath         = "/api/lobby/{id}/wait"
	LobbyApprovePath      = "/api/lobby/{id}/approve"
	LobbyDenyPath         = "/api/lobby/{id}/deny"
	LiveKitWebhookPath    = "/api/webhooks/media"
	RecordingStartPath    = "/api/rooms/{slug}/recording/start"
	RecordingStopPath     = "/api/rooms/{slug}/recording/stop"
	RoomRecordingsPath    = "/api/rooms/{slug}/recordings"
	RecordingPath         = "/api/recordings/{id}"
	RecordingDownloadPath = "/api/recordings/{id}/download"

	// Transcripts and the machines that make them (ARCHITECTURE.md §8.1).
	RecordingTranscriptPath         = "/api/recordings/{id}/transcript"
	RecordingTranscriptDownloadPath = "/api/recordings/{id}/transcript/download"
	MachinesPath                    = "/api/machines"
	MachinePath                     = "/api/machines/{id}"
	PairingPath                     = "/api/machines/pairings/{code}"
	PairingConfirmPath              = "/api/machines/pairings/{code}/confirm"
	PairingDenyPath                 = "/api/machines/pairings/{code}/deny"
	// MoilBasePath is where the moil SDK serves machines: the moil base URL
	// is the base URL plus this path.
	MoilBasePath = "/moil"
)

type TokenResponse struct {
	Token string `json:"token"`
	WSURL string `json:"ws_url"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}

type Me struct {
	Sub   string `json:"sub"`
	Email string `json:"email"`
	Name  string `json:"name"`
	// Transcripts is true when this deployment runs transcripts and machine
	// pairing (TIDE_TRANSCRIPTS, ARCHITECTURE.md §8.1). When false the SPA
	// hides /machines and every transcript control; the routes 404.
	Transcripts bool `json:"transcripts"`
	// Recording is true when this deployment records meetings: hosts sign in
	// and object storage is configured (ARCHITECTURE.md §8). When false the
	// SPA hides the record control and every recording list; the routes 404.
	Recording bool `json:"recording"`
	// Anonymous is true when this deployment has no sign-in
	// (ARCHITECTURE.md §4.1): the session is an anonymous one that owns the
	// rooms this browser created, and Email and Name are empty. The SPA shows
	// no account and no sign-out.
	Anonymous bool `json:"anonymous"`
}

type RoomInfo struct {
	ID           string `json:"id"`
	Slug         string `json:"slug"`
	Name         string `json:"name"`
	LobbyEnabled bool   `json:"lobby_enabled"`
	CreatedAt    int64  `json:"created_at"`
	// Live state from LiveKit, populated only on the list path (the create,
	// update, and single-room paths do not query the SFU, so these stay zero
	// there). Active is true when the room currently has participants.
	Active          bool `json:"active"`
	NumParticipants int  `json:"num_participants"`
	Recording       bool `json:"recording"`
	// LastActiveAt is Unix seconds of the most recent participant join, or null
	// if the room has never been used.
	LastActiveAt *int64 `json:"last_active_at"`
}

type PublicRoomInfo struct {
	Slug         string `json:"slug"`
	Name         string `json:"name"`
	LobbyEnabled bool   `json:"lobby_enabled"`
	// CanManage is true when the requesting session owns this room or is a
	// global administrator. The capability is enforced server-side on every route.
	CanManage bool `json:"can_manage"`
}

// CreateRoomRequest: both fields are optional (ARCHITECTURE.md §5). A blank
// name becomes the room's slug; a missing slug is generated by the server,
// while a given one is validated and answers 409 when taken.
type CreateRoomRequest struct {
	Name string  `json:"name,omitempty"`
	Slug *string `json:"slug,omitempty"`
}

type UpdateRoomRequest struct {
	Name         *string `json:"name,omitempty"`
	Slug         *string `json:"slug,omitempty"`
	LobbyEnabled *bool   `json:"lobby_enabled,omitempty"`
}

type JoinRequest struct {
	Name string `json:"name"`
}

type JoinResponse struct {
	Status    string `json:"status"`
	Token     string `json:"token,omitempty"`
	WSURL     string `json:"ws_url,omitempty"`
	RequestID string `json:"request_id,omitempty"`
}

type LobbyRequestInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	RequestedAt int64  `json:"requested_at"`
}

type LobbyWaitingSSE struct {
	Status string `json:"status"`
}

type LobbyAdmittedSSE struct {
	Token string `json:"token"`
	WSURL string `json:"ws_url"`
}

type LobbyDeniedSSE struct{}

type LobbyPendingSSE struct {
	Requests []LobbyRequestInfo `json:"requests"`
}

// RecordingStartRequest selects the recording mode. Recordings are
// audio-only by default; Video opts into the full composite. The body is
// optional — an empty request means the defaults.
type RecordingStartRequest struct {
	Video bool `json:"video"`
}

type RecordingInfo struct {
	ID        string  `json:"id"`
	RoomSlug  string  `json:"room_slug"`
	EgressID  string  `json:"egress_id"`
	Status    string  `json:"status"`
	StartedBy string  `json:"started_by"`
	StartedAt int64   `json:"started_at"`
	AudioOnly bool    `json:"audio_only"`
	EndedAt   *int64  `json:"ended_at"`
	DurationS *int64  `json:"duration_s"`
	S3Key     *string `json:"s3_key"`
	SizeBytes *int64  `json:"size_bytes"`
	// Transcript is null when the recording has no transcript and can't get
	// one: it isn't completed, or its room's owner has no paired machine.
	// Only the list path fills it in.
	Transcript *TranscriptInfo `json:"transcript"`
}

// Transcript statuses (ARCHITECTURE.md §8.1).
const (
	// TranscriptAvailable: a completed recording whose room owner has a
	// machine, with no transcript requested yet.
	TranscriptAvailable = "available"
	// TranscriptWaiting: requested, and no machine is working on it.
	TranscriptWaiting = "waiting"
	// TranscriptRunning: a machine is working on it.
	TranscriptRunning = "running"
	// TranscriptCompleted: ready to download.
	TranscriptCompleted = "completed"
	// TranscriptFailed: the last job failed; requesting again retries.
	TranscriptFailed = "failed"
)

// The transcript download's format query parameter.
const (
	// TranscriptFormatText is the readable transcript: one line per
	// utterance, with its time and speaker.
	TranscriptFormatText = "txt"
	// TranscriptFormatVTT is WebVTT captions, which players load beside the
	// recording.
	TranscriptFormatVTT = "vtt"
)

type TranscriptInfo struct {
	// Status is one of the Transcript* statuses.
	Status string `json:"status"`
	// Progress is the running job's progress from 0 to 1, when its machine
	// reported one.
	Progress *float64 `json:"progress"`
	// Message explains a waiting transcript (why no machine is on it) or
	// describes a running one's current step.
	Message string `json:"message,omitempty"`
	// Error says why a failed transcript failed.
	Error string `json:"error,omitempty"`
	// Speakers is how many speakers a completed transcript found.
	Speakers *int `json:"speakers"`
}

// MachinesResponse lists the signed-in host's paired machines.
type MachinesResponse struct {
	Machines []MachineInfo `json:"machines"`
	// Bundle is the transcription bundle tide publishes; a machine takes
	// transcript jobs only once its owner approved exactly this hash.
	Bundle BundleInfo `json:"bundle"`
	// MoilURL is the address the moil app pairs with, e.g.
	// https://tide.example.com/moil.
	MoilURL string `json:"moil_url"`
	// AppURL is where hosts get the moil app: its latest release, as the
	// moil SDK names it (moil.AppURL).
	AppURL string `json:"app_url"`
}

type MachineInfo struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	OS         string `json:"os"`
	Arch       string `json:"arch"`
	AppVersion string `json:"app_version"`
	PairedAt   int64  `json:"paired_at"`
	// LastSeenAt is Unix seconds of the machine's last connection or report,
	// or null if it never connected.
	LastSeenAt *int64 `json:"last_seen_at"`
	// State is one of the Machine* states.
	State string `json:"state"`
	// Approved is true when the machine last reported MachinesResponse.Bundle
	// as approved by its owner.
	Approved bool `json:"approved"`
}

// Machine states (MachineInfo.State).
const (
	// MachineIdle: connected and able to take a job.
	MachineIdle = "idle"
	// MachineBusy: connected and running a job, for tide or another service.
	MachineBusy = "busy"
	// MachinePaused: connected, and its owner paused it in the moil app.
	MachinePaused = "paused"
	// MachineOffline: not connected.
	MachineOffline = "offline"
)

type BundleInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
	Hash    string `json:"hash"`
}

// PairingInfo is a machine waiting for a signed-in host to confirm its code.
type PairingInfo struct {
	// Code is the user code the moil app shows, formatted XXXX-XXXX.
	Code       string `json:"code"`
	Name       string `json:"name"`
	OS         string `json:"os"`
	Arch       string `json:"arch"`
	AppVersion string `json:"app_version"`
	ExpiresAt  int64  `json:"expires_at"`
	// MoilURL is tide's moil address, which the machine's moil app must
	// show it is pairing with: a pairing relayed through another address
	// shows the same code, so this is the host's check that it isn't one.
	MoilURL string `json:"moil_url"`
}
